//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.25 at 06:03:44 PM MESZ 
//


package zap.report;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the zap.report package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: zap.report
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OWASPZAPReport.Site.Alerts.Alertitem.Instances.Instance }
     * 
     */
    public OWASPZAPReport.Site.Alerts.Alertitem.Instances.Instance createOWASPZAPReportSiteAlertsAlertitemInstancesInstance() {
        return new OWASPZAPReport.Site.Alerts.Alertitem.Instances.Instance();
    }

    /**
     * Create an instance of {@link OWASPZAPReport.Site.Alerts }
     * 
     */
    public OWASPZAPReport.Site.Alerts createOWASPZAPReportSiteAlerts() {
        return new OWASPZAPReport.Site.Alerts();
    }

    /**
     * Create an instance of {@link OWASPZAPReport.Site.Alerts.Alertitem.Instances }
     * 
     */
    public OWASPZAPReport.Site.Alerts.Alertitem.Instances createOWASPZAPReportSiteAlertsAlertitemInstances() {
        return new OWASPZAPReport.Site.Alerts.Alertitem.Instances();
    }

    /**
     * Create an instance of {@link OWASPZAPReport }
     * 
     */
    public OWASPZAPReport createOWASPZAPReport() {
        return new OWASPZAPReport();
    }

    /**
     * Create an instance of {@link OWASPZAPReport.Site.Alerts.Alertitem }
     * 
     */
    public OWASPZAPReport.Site.Alerts.Alertitem createOWASPZAPReportSiteAlertsAlertitem() {
        return new OWASPZAPReport.Site.Alerts.Alertitem();
    }

    /**
     * Create an instance of {@link OWASPZAPReport.Site }
     * 
     */
    public OWASPZAPReport.Site createOWASPZAPReportSite() {
        return new OWASPZAPReport.Site();
    }

}
