//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.25 at 06:03:44 PM MESZ 
//


package zap.report;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="site">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="alerts">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="alertitem" maxOccurs="unbounded" minOccurs="0">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="pluginid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="alert" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="riskcode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="confidence" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="riskdesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="instances">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="instance" maxOccurs="unbounded" minOccurs="0">
 *                                                   &lt;complexType>
 *                                                     &lt;complexContent>
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                         &lt;sequence>
 *                                                           &lt;element name="uri" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                                                           &lt;element name="method" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                                           &lt;element name="evidence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                                           &lt;element name="param" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                                           &lt;element name="attack" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                                         &lt;/sequence>
 *                                                       &lt;/restriction>
 *                                                     &lt;/complexContent>
 *                                                   &lt;/complexType>
 *                                                 &lt;/element>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                       &lt;element name="count" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="solution" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="otherinfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                       &lt;element name="reference" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="cweid" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                                       &lt;element name="wascid" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                       &lt;element name="sourceid" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="host" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *                 &lt;attribute name="port" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                 &lt;attribute name="ssl" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="generated" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "site"
})
@XmlRootElement(name = "OWASPZAPReport")
public class OWASPZAPReport {

    @XmlElement(required = true)
    protected OWASPZAPReport.Site site;
    @XmlAttribute(name = "generated")
    protected String generated;
    @XmlAttribute(name = "version")
    protected String version;

    /**
     * Gets the value of the site property.
     * 
     * @return
     *     possible object is
     *     {@link OWASPZAPReport.Site }
     *     
     */
    public OWASPZAPReport.Site getSite() {
        return site;
    }

    /**
     * Sets the value of the site property.
     * 
     * @param value
     *     allowed object is
     *     {@link OWASPZAPReport.Site }
     *     
     */
    public void setSite(OWASPZAPReport.Site value) {
        this.site = value;
    }

    /**
     * Gets the value of the generated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGenerated() {
        return generated;
    }

    /**
     * Sets the value of the generated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGenerated(String value) {
        this.generated = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="alerts">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="alertitem" maxOccurs="unbounded" minOccurs="0">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="pluginid" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="alert" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="riskcode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="confidence" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="riskdesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="instances">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="instance" maxOccurs="unbounded" minOccurs="0">
     *                                         &lt;complexType>
     *                                           &lt;complexContent>
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                               &lt;sequence>
     *                                                 &lt;element name="uri" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *                                                 &lt;element name="method" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                                                 &lt;element name="evidence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                                                 &lt;element name="param" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                                                 &lt;element name="attack" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                                               &lt;/sequence>
     *                                             &lt;/restriction>
     *                                           &lt;/complexContent>
     *                                         &lt;/complexType>
     *                                       &lt;/element>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                             &lt;element name="count" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="solution" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="otherinfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                             &lt;element name="reference" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="cweid" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *                             &lt;element name="wascid" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                             &lt;element name="sourceid" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="host" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
     *       &lt;attribute name="port" type="{http://www.w3.org/2001/XMLSchema}short" />
     *       &lt;attribute name="ssl" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "alerts"
    })
    public static class Site {

        @XmlElement(required = true)
        protected OWASPZAPReport.Site.Alerts alerts;
        @XmlAttribute(name = "host")
        protected String host;
        @XmlAttribute(name = "name")
        @XmlSchemaType(name = "anyURI")
        protected String name;
        @XmlAttribute(name = "port")
        protected Short port;
        @XmlAttribute(name = "ssl")
        protected String ssl;

        /**
         * Gets the value of the alerts property.
         * 
         * @return
         *     possible object is
         *     {@link OWASPZAPReport.Site.Alerts }
         *     
         */
        public OWASPZAPReport.Site.Alerts getAlerts() {
            return alerts;
        }

        /**
         * Sets the value of the alerts property.
         * 
         * @param value
         *     allowed object is
         *     {@link OWASPZAPReport.Site.Alerts }
         *     
         */
        public void setAlerts(OWASPZAPReport.Site.Alerts value) {
            this.alerts = value;
        }

        /**
         * Gets the value of the host property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHost() {
            return host;
        }

        /**
         * Sets the value of the host property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHost(String value) {
            this.host = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the port property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getPort() {
            return port;
        }

        /**
         * Sets the value of the port property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setPort(Short value) {
            this.port = value;
        }

        /**
         * Gets the value of the ssl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSsl() {
            return ssl;
        }

        /**
         * Sets the value of the ssl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSsl(String value) {
            this.ssl = value;
        }
        
        


        @Override
		public String toString() {
			return "Site [alerts=" + alerts + ", host=" + host + ", name=" + name + ", port=" + port + ", ssl=" + ssl
					+ "]";
		}
        




		/**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="alertitem" maxOccurs="unbounded" minOccurs="0">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="pluginid" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="alert" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="riskcode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="confidence" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="riskdesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="instances">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="instance" maxOccurs="unbounded" minOccurs="0">
         *                               &lt;complexType>
         *                                 &lt;complexContent>
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                     &lt;sequence>
         *                                       &lt;element name="uri" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
         *                                       &lt;element name="method" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                                       &lt;element name="evidence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                                       &lt;element name="param" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                                       &lt;element name="attack" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                                     &lt;/sequence>
         *                                   &lt;/restriction>
         *                                 &lt;/complexContent>
         *                               &lt;/complexType>
         *                             &lt;/element>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                   &lt;element name="count" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="solution" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="otherinfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                   &lt;element name="reference" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="cweid" type="{http://www.w3.org/2001/XMLSchema}short"/>
         *                   &lt;element name="wascid" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                   &lt;element name="sourceid" type="{http://www.w3.org/2001/XMLSchema}byte"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "alertitem"
        })
        public static class Alerts {

            protected List<OWASPZAPReport.Site.Alerts.Alertitem> alertitem;

            /**
             * Gets the value of the alertitem property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the alertitem property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getAlertitem().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link OWASPZAPReport.Site.Alerts.Alertitem }
             * 
             * 
             */
            public List<OWASPZAPReport.Site.Alerts.Alertitem> getAlertitem() {
                if (alertitem == null) {
                    alertitem = new ArrayList<OWASPZAPReport.Site.Alerts.Alertitem>();
                }
                return this.alertitem;
            }

            


			/**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="pluginid" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="alert" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="riskcode" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="confidence" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="riskdesc" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="desc" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="instances">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="instance" maxOccurs="unbounded" minOccurs="0">
             *                     &lt;complexType>
             *                       &lt;complexContent>
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                           &lt;sequence>
             *                             &lt;element name="uri" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
             *                             &lt;element name="method" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                             &lt;element name="evidence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *                             &lt;element name="param" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *                             &lt;element name="attack" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *                           &lt;/sequence>
             *                         &lt;/restriction>
             *                       &lt;/complexContent>
             *                     &lt;/complexType>
             *                   &lt;/element>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *         &lt;element name="count" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="solution" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="otherinfo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *         &lt;element name="reference" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="cweid" type="{http://www.w3.org/2001/XMLSchema}short"/>
             *         &lt;element name="wascid" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *         &lt;element name="sourceid" type="{http://www.w3.org/2001/XMLSchema}byte"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "pluginid",
                "alert",
                "name",
                "riskcode",
                "confidence",
                "riskdesc",
                "desc",
                "instances",
                "count",
                "solution",
                "otherinfo",
                "reference",
                "cweid",
                "wascid",
                "sourceid"
            })
            public static class Alertitem {

                protected int pluginid;
                @XmlElement(required = true)
                protected String alert;
                @XmlElement(required = true)
                protected String name;
                protected byte riskcode;
                protected byte confidence;
                @XmlElement(required = true)
                protected String riskdesc;
                @XmlElement(required = true)
                protected String desc;
                @XmlElement(required = true)
                protected OWASPZAPReport.Site.Alerts.Alertitem.Instances instances;
                protected byte count;
                @XmlElement(required = true)
                protected String solution;
                protected String otherinfo;
                @XmlElement(required = true)
                protected String reference;
                protected short cweid;
                protected byte wascid;
                protected byte sourceid;

                /**
                 * Gets the value of the pluginid property.
                 * 
                 */
                public int getPluginid() {
                    return pluginid;
                }

                /**
                 * Sets the value of the pluginid property.
                 * 
                 */
                public void setPluginid(int value) {
                    this.pluginid = value;
                }

                /**
                 * Gets the value of the alert property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getAlert() {
                    return alert;
                }

                /**
                 * Sets the value of the alert property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setAlert(String value) {
                    this.alert = value;
                }

                /**
                 * Gets the value of the name property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getName() {
                    return name;
                }

                /**
                 * Sets the value of the name property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setName(String value) {
                    this.name = value;
                }

                /**
                 * Gets the value of the riskcode property.
                 * 
                 */
                public byte getRiskcode() {
                    return riskcode;
                }

                /**
                 * Sets the value of the riskcode property.
                 * 
                 */
                public void setRiskcode(byte value) {
                    this.riskcode = value;
                }

                /**
                 * Gets the value of the confidence property.
                 * 
                 */
                public byte getConfidence() {
                    return confidence;
                }

                /**
                 * Sets the value of the confidence property.
                 * 
                 */
                public void setConfidence(byte value) {
                    this.confidence = value;
                }

                /**
                 * Gets the value of the riskdesc property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRiskdesc() {
                    return riskdesc;
                }

                /**
                 * Sets the value of the riskdesc property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRiskdesc(String value) {
                    this.riskdesc = value;
                }

                /**
                 * Gets the value of the desc property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getDesc() {
                    return desc;
                }

                /**
                 * Sets the value of the desc property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setDesc(String value) {
                    this.desc = value;
                }

                /**
                 * Gets the value of the instances property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link OWASPZAPReport.Site.Alerts.Alertitem.Instances }
                 *     
                 */
                public OWASPZAPReport.Site.Alerts.Alertitem.Instances getInstances() {
                    return instances;
                }

                /**
                 * Sets the value of the instances property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link OWASPZAPReport.Site.Alerts.Alertitem.Instances }
                 *     
                 */
                public void setInstances(OWASPZAPReport.Site.Alerts.Alertitem.Instances value) {
                    this.instances = value;
                }

                /**
                 * Gets the value of the count property.
                 * 
                 */
                public byte getCount() {
                    return count;
                }

                /**
                 * Sets the value of the count property.
                 * 
                 */
                public void setCount(byte value) {
                    this.count = value;
                }

                /**
                 * Gets the value of the solution property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSolution() {
                    return solution;
                }

                /**
                 * Sets the value of the solution property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSolution(String value) {
                    this.solution = value;
                }

                /**
                 * Gets the value of the otherinfo property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getOtherinfo() {
                    return otherinfo;
                }

                /**
                 * Sets the value of the otherinfo property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setOtherinfo(String value) {
                    this.otherinfo = value;
                }

                /**
                 * Gets the value of the reference property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getReference() {
                    return reference;
                }

                /**
                 * Sets the value of the reference property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setReference(String value) {
                    this.reference = value;
                }

                /**
                 * Gets the value of the cweid property.
                 * 
                 */
                public short getCweid() {
                    return cweid;
                }

                /**
                 * Sets the value of the cweid property.
                 * 
                 */
                public void setCweid(short value) {
                    this.cweid = value;
                }

                /**
                 * Gets the value of the wascid property.
                 * 
                 */
                public byte getWascid() {
                    return wascid;
                }

                /**
                 * Sets the value of the wascid property.
                 * 
                 */
                public void setWascid(byte value) {
                    this.wascid = value;
                }

                /**
                 * Gets the value of the sourceid property.
                 * 
                 */
                public byte getSourceid() {
                    return sourceid;
                }

                /**
                 * Sets the value of the sourceid property.
                 * 
                 */
                public void setSourceid(byte value) {
                    this.sourceid = value;
                }
                
                
                

                @Override
				public String toString() {
					return "Alertitem [pluginid=" + pluginid + ", alert=" + alert + ", name=" + name + ", riskcode="
							+ riskcode + ", confidence=" + confidence + ", riskdesc=" + riskdesc + ", desc=" + desc
							+ ", instances=" + instances + ", count=" + count + ", solution=" + solution
							+ ", otherinfo=" + otherinfo + ", reference=" + reference + ", cweid=" + cweid + ", wascid="
							+ wascid + ", sourceid=" + sourceid + "]";
				}





				/**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="instance" maxOccurs="unbounded" minOccurs="0">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="uri" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
                 *                   &lt;element name="method" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *                   &lt;element name="evidence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                 *                   &lt;element name="param" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                 *                   &lt;element name="attack" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "instance"
                })
                public static class Instances {

                    protected List<OWASPZAPReport.Site.Alerts.Alertitem.Instances.Instance> instance;

                    /**
                     * Gets the value of the instance property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the instance property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getInstance().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link OWASPZAPReport.Site.Alerts.Alertitem.Instances.Instance }
                     * 
                     * 
                     */
                    public List<OWASPZAPReport.Site.Alerts.Alertitem.Instances.Instance> getInstance() {
                        if (instance == null) {
                            instance = new ArrayList<OWASPZAPReport.Site.Alerts.Alertitem.Instances.Instance>();
                        }
                        return this.instance;
                    }
                    
                    
                    @Override
					public String toString() {
						return "Instances [instance=" + instance + ", getInstance()=" + getInstance() + "]";
					}




					/**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="uri" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
                     *         &lt;element name="method" type="{http://www.w3.org/2001/XMLSchema}string"/>
                     *         &lt;element name="evidence" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                     *         &lt;element name="param" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                     *         &lt;element name="attack" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "uri",
                        "method",
                        "evidence",
                        "param",
                        "attack"
                    })
                    public static class Instance {

                        @XmlElement(required = true)
                        @XmlSchemaType(name = "anyURI")
                        protected String uri;
                        @XmlElement(required = true)
                        protected String method;
                        protected String evidence;
                        protected String param;
                        protected String attack;

                        /**
                         * Gets the value of the uri property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getUri() {
                            return uri;
                        }

                        /**
                         * Sets the value of the uri property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setUri(String value) {
                            this.uri = value;
                        }

                        /**
                         * Gets the value of the method property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getMethod() {
                            return method;
                        }

                        /**
                         * Sets the value of the method property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setMethod(String value) {
                            this.method = value;
                        }

                        /**
                         * Gets the value of the evidence property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getEvidence() {
                            return evidence;
                        }

                        /**
                         * Sets the value of the evidence property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setEvidence(String value) {
                            this.evidence = value;
                        }

                        /**
                         * Gets the value of the param property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getParam() {
                            return param;
                        }

                        /**
                         * Sets the value of the param property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setParam(String value) {
                            this.param = value;
                        }

                        /**
                         * Gets the value of the attack property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getAttack() {
                            return attack;
                        }

                        /**
                         * Sets the value of the attack property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setAttack(String value) {
                            this.attack = value;
                        }

						@Override
						public String toString() {
							return "Instance [uri=" + uri + ", method=" + method + ", evidence=" + evidence + ", param="
									+ param + ", attack=" + attack + "]";
						}
                        
                        

                    }

                }

            }

        }

    }

}
