server:
  port: 8761
#  context-path: v2
  


  

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    
#springfox.documentation.swagger.v2.path=/swagger.json
    
    # prefix for all requests
#server.contextPath=/v2

# location of the swagger json
