server:
  port: 8761
#  context-path: v2
  


  

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
    
spring:
  datasource:
    url:
    username: 
    password: 
    platform: mysql
    initialize: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
    spring.jpa.show-sql: true
    hibernate.ddl-auto: update
    
    
    
#springfox.documentation.swagger.v2.path=/swagger.json
    
    # prefix for all requests
#server.contextPath=/v2

# location of the swagger json
